### ISSUE TITLE
tsa.seasonal_decompose frequency interpretation

### ISSUE THREAD

**Issue by dillontiner** [statsmodels/statsmodels#3085]
I was trying to use seasonal_decompose for time series analysis with a pandas dataframe with a datetime index for every 5 minutes. This threw an error that came from statsmodels/tsa/tsatools.py:
`656         raise ValueError("freq {} not understood. Please report if you "`
`--> 657                          "think this in error.".format(freq))`
which came through statsmodels/tsa/seasonal.py:
`69     if pfreq is not None:`
`---> 70         pfreq = freq_to_period(pfreq)`
Looking at the source code in tsatools.py, there are lines for interpreting annual, quarterly, monthly, weekly, daily, business day, and hourly, but not anything representing minutes (freq='5T' in my case):

` def freq_to_period(freq):

```
Convert a pandas frequency to a periodicity
Parameters
----------
freq : str or offset
    Frequency to convert
Returns
-------
period : int
    Periodicity of freq
Notes
-----
Annual maps to 1, quarterly maps to 4, monthly to 12, weekly to 52.

if not isinstance(freq, offsets.DateOffset):
    freq = to_offset(freq)  # go ahead and standardize
freq = freq.rule_code.upper()

if freq == 'A' or freq.startswith(('A-', 'AS-')):
    return 1
elif freq == 'Q' or freq.startswith(('Q-', 'QS-')):
    return 4
elif freq == 'M' or freq.startswith(('M-', 'MS')):
    return 12
elif freq == 'W' or freq.startswith('W-'):
    return 52
elif freq == 'D':
    return 7
elif freq == 'B':
    return 5
elif freq == 'H':
    return 24
else:  # pragma : no cover
    raise ValueError("freq {} not understood. Please report if you "
                     "think this in error.".format(freq))`
```

If I change my datetime index to one week 'W', the seasonal_decompose function runs just fine. However, if I try to use one day 'D', it throws the same error I get from '5T'. The problem is simply that, for a frequency that it seems to be build to handle, it throws the same error as it does for one it is not built to handle.

**Comment by josef-pkt** [comment]
Are you using master or 0.8.0rc1?

The problem is that in cases like 5 minute periods it is difficult to guess what the season length should be. (When in doubt, refuse to guess.)
In 0.8 and master explicitly specifying `freq` should override any pandas index and implied freq. (If not, then it would be a bug in recent changes.)

(I think the ValueError message should be improved, because this is a frequently encountered problem, FEP?)

**Comment by dillontiner** [comment]
I am looking at the master branch and I am working with version 0.6.1.

Passing a freq parameter to seasonal decompose also doesn't work unless it is consistent with the pandas datetime index. Even if it is consistent, it still doesn't accept days as an interpretable freq for the index.

**Comment by ChadFulton** [comment]
Can you post something minimal that replicates the problem? When I use a day-indexed time series it works.

> Passing a freq parameter to seasonal decompose also doesn't work unless it is consistent with the pandas datetime index.

Can you give an example of what you're doing / expecting? The `freq` parameter expects an integer describing the periodicity of the seasonality. If this parameter is passed, then the `freq_to_period` function you referenced above, which throws the `ValueError`, shouldn't be called.

------------

Here are some examples of what I mean:

```console
>>> nobs = 100
>>> index = pd.date_range('1950-01-01', freq='D', periods=nobs)
>>> endog = pd.Series(np.random.normal(size=nobs), index=index)
>>> print(sm.tsa.seasonal_decompose(endog).seasonal)
1950-01-01   -0.019085
1950-01-02    0.429137
...
>>> print(sm.tsa.seasonal_decompose(endog, freq=30).seasonal)
1950-01-01    -0.631887
1950-01-02     -1.110126
...
>>> index = pd.date_range('1950-01-01', freq='5T', periods=nobs)
>>> endog = pd.Series(np.random.normal(size=nobs), index=index)
>>> print(sm.tsa.seasonal_decompose(endog).seasonal)
...
ValueError: freq T not understood. Please report if you think this in error.
>>> print(sm.tsa.seasonal_decompose(endog).seasonal, freq=30)
1950-01-01 00:00:00   -0.631887
1950-01-01 00:05:00   -1.110126
```

**Comment by josef-pkt** [comment]
In 0.6.1 specifying `freq` was just ignored if a pandas Series was used. `freq` works and worked with numpy arrays.
This has been fixed in 0.8.0.rc1 and in master.

**Comment by S4lem** [comment]
Hi everybody,

First of all, thank you for your great work.

@josef-pkt 
> The problem is that in cases like 5 minute periods it is difficult to guess what the season length should be

I have the same problem, my frequency is 5T, but I still don't understand why it isn't possible to make a seasonal decomposition

**Comment by cem94** [comment]
> Hi everybody,
> 
> First of all, thank you for your great work.
> 
> @josef-pkt
> 
> > The problem is that in cases like 5 minute periods it is difficult to guess what the season length should be
> 
> I have the same problem, my frequency is 5T, but I still don't understand why it isn't possible to make a seasonal decomposition


Have you found any solution?

**Comment by bashtage** [comment]
This works correctly by manually setting `freq` to an integer.
