### ISSUE TITLE
pandas.core.datetools module is deprecated and will be removed in a future version.

### ISSUE THREAD

**Issue by sbasumal** [statsmodels/statsmodels#3814]
Code:

from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, \
    load_robot_execution_failures
download_robot_execution_failures()
timeseries, y = load_robot_execution_failures()

Issue:
c:\python36-32\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

Expected output:
Features

I have installed Python and all its associated libraries today. I get this issue when i try running sample tutorial codes.

**Comment by bashtage** [comment]
This has been fixed in statsmodels master.

**Comment by TomAugspurger** [comment]
https://github.com/statsmodels/statsmodels/pull/3618

**Comment by Make42** [comment]
In which version has this fix been added to? The newest version for anaconda is 0.8.0 and the warning still exists there. Could the anaconda version, please be updated?

**Comment by horitahiroshi** [comment]
Hello.
I tried import the statsmodels.api in my python script and got the following:

miniconda2/lib/python2.7/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

Then I tried to update and clone the statsmodels master, but still got same error message.
What should I do?

**Comment by paulwasit** [comment]
It seems that the module `pandas.tseries.tools` has been removed. In the pandas code, the deprecated  datetools module went from:

```
from pandas.tseries.tools import *
```

to 

```
from pandas.core.tools.datetimes import *
``` 


So maybe the proper import would be `pandas.core.tools.datetimes as datetools`  in `compat/pandas.py`?

**Comment by TomAugspurger** [comment]
Nope, `pandas.core` is private to pandas: http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#reorganization-of-the-library-privacy-changes

**Comment by paulwasit** [comment]
By bad, I had not seen that. But then what would be the proper import? `pandas.tseries.tools` does not exist under this name anymore.

**Comment by horitahiroshi** [comment]
I've done `pip freeze` to see the version of my python libs and updated the pandas lib by doing `pip install pandas==0.19.*`, because that's the version required by statsmodels (as I remember).
After the code ran finely (till now).

**Comment by drorata** [comment]
Is it indeed the case, that `statsmodels` is not compatible with `pandas` 0.22?

**Comment by TomAugspurger** [comment]
Statsmodels 0.8, the currently released version, works but that warning is
emitted (and you can silence specific warnings if you want).

AFAIK, statsmodels master is compatible with pandas master.

**Comment by jaypeedevlin** [comment]
Is there a view to release anytime soon - The change was made 9 months ago and the statsmodels team haven't found their way clear to pushing it out!

**Comment by TomAugspurger** [comment]
I don't think that anyone is given time to work on statsmodels as part of
their day job. It's purely volunteer on nights and weekends.

I'm busy with pandas 0.23 development for the next few weeks. After that I
can try to help with a release. You can help by flagging
issues that are blocking the release and ensuring that the documentation
builds correctly.

**Comment by ryanjmccall** [comment]
```
np.warnings.filterwarnings("ignore")
from pandas.core import datetools
np.warnings.resetwarnings()
```

**Comment by saitzaw** [comment]
I use pd.to_datetime() to solve this problem.
