### ISSUE TITLE
Unable to install statsmodels on Python 3.8

### ISSUE THREAD

**Issue by tochukwuokafor** [statsmodels/statsmodels#6454]
Hello,

I have tried installing statsmodels on my computer, but it's not working. I used `python3 -m pip install statsmodels` command on my command window. My computer is a 64-bit Microsoft Windows 10 HP Envy. I have attached a picture of the error message that I receive:

From what I can see, the major errors include: "Could not build wheels for statsmodels which use PEP 517 and cannot be installed directly", "Failed building wheel for statsmodel". (I don't even know what PEP 517 is).

Please can anyone assist? Thank you.
![image](https://user-images.githubusercontent.com/30937231/72905539-b1c41980-3cfe-11ea-8a86-6e72b3d9f39b.png)
![image](https://user-images.githubusercontent.com/30937231/72905647-dd470400-3cfe-11ea-87c7-8346e16a748e.png)

**Comment by bashtage** [comment]
Can you try again now?  The wheels were in the process of being uploaded when you opened this issue.

**Comment by bashtage** [comment]
I think this is solved since wheels are available. Please let us know if it continues

**Comment by tochukwuokafor** [comment]
I still get the same error when I run `python3 -m pip install statsmodels` Please what could be the problem?

**Comment by tochukwuokafor** [comment]
Here is the final error message:

![image](https://user-images.githubusercontent.com/30937231/72921004-6dde0e00-3d18-11ea-97ca-228be649a313.png)

**Comment by bashtage** [comment]
Do your numpy and scipy work correctly, say, in an Ipython session?

**Comment by bashtage** [comment]
You can also try

pip install statsmodels==0.10.2

which will install an old version as a temporary fix.

**Comment by tochukwuokafor** [comment]
My numpy and scipy works fine without returning errors as shown here:

![image](https://user-images.githubusercontent.com/30937231/72921530-69662500-3d19-11ea-8382-1779bf5bf4b9.png)

**Comment by tochukwuokafor** [comment]
`pip install statsmodels==0.10.2` works. But it seems like an old version.

![image](https://user-images.githubusercontent.com/30937231/72921606-94e90f80-3d19-11ea-8c77-9ca545f92c94.png)

**Comment by bashtage** [comment]
Thanks for the report.  I found the issue.  

Try `pip install statsmodels --upgrade` now. The wheel for Pyhon 3.7 on Win64 was missing.

**Comment by tochukwuokafor** [comment]
Thanks. It works now!

**Comment by ChenChingChih** [comment]
Hi, 
I face a similar problem when I install statsmodels via git from source.
The operator system I use is a 64-bit Microsoft Windows 10 with Python 3.7.4 and pip 20.0.2.
I need to install from source since I need a fix in statsmodel which is not yet update to published version ([#6606](https://github.com/statsmodels/statsmodels/issues/6606#issuecomment-604797112) )
 ### error message
1.

    (base) C:\Users\ChingChih>pip install git+https://github.com/statsmodels/statsmodels.git
     Collecting git+https://github.com/statsmodels/statsmodels.git
     Cloning https://github.com/statsmodels/statsmodels.git to 
     c:\users\chingc~1\appdata\local\temp\pip-req-build-sihj_3hh
     Running command git clone -q https://github.com/statsmodels/statsmodels.git 
     'C:\Users\CHINGC~1\AppData\Local\Temp\pip-req-build-sihj_3hh'
     Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
    Requirement already satisfied: numpy>=1.15 in c:\users\chingchih\anaconda3\lib\site-packages 
    (from statsmodels==0.12.0.dev0+136.gc3bd7d369) (1.18.1)
    Collecting patsy>=0.5
    Using cached patsy-0.5.1-py2.py3-none-any.whl (231 kB)
    Requirement already satisfied: scipy>=1.1 in c:\users\chingchih\anaconda3\lib\site-packages (from 
    statsmodels==0.12.0.dev0+136.gc3bd7d369) (1.4.1) 
    Requirement already satisfied: pandas>=0.21 in c:\users\chingchih\anaconda3\lib\site-packages 
    (from statsmodels==0.12.0.dev0+136.gc3bd7d369) (1.0.3)
    Requirement already satisfied: six in c:\users\chingchih\anaconda3\lib\site-packages (from 
    patsy>=0.5->statsmodels==0.12.0.dev0+136.gc3bd7d369) (1.14.0)
    Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\chingchih\anaconda3\lib\site - 
    packages (from pandas>=0.21->statsmodels==0.12.0.dev0+136.gc3bd7d369) (2.8.1)
    Requirement already satisfied: pytz>=2017.2 in c:\users\chingchih\anaconda3\lib\site-packages 
    (from pandas>=0.21->statsmodels==0.12.0.dev0+136.gc3bd7d369) (2019.3)
    Building wheels for collected packages: statsmodels
    Building wheel for statsmodels (PEP 517) ... error
    ERROR: Command errored out with exit status 1:
    command: 'C:\Users\ChingChih\Anaconda3\python.exe' 'C:\Users\ChingChih\Anaconda3\lib\site- 
    packages\pip\_vendor\pep517\_in_process.py' build_wheel 
    'C:\Users\CHINGC~1\AppData\Local\Temp\tmp5ionj_il'
       cwd: C:\Users\CHINGC~1\AppData\Local\Temp\pip-req-build-ilqj70my 

2. 

     UPDATING build\lib.win-amd64-3.7\statsmodels/_version.py  
     set build\lib.win-amd64-3.7\statsmodels/_version.py to '0.12.0.dev0+136.gc3bd7d369'
     running build_ext
    _stl.c
    c:\users\chingchih\anaconda3\include\pyconfig.h(203): fatal error C1083: 無法開啟包含檔案: 
    'basetsd.h': No such file or directory
     error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c   
    /nologo /Ox /W3 /GL /DNDEBUG /MD -DCYTHON_TRACE_NOGIL=0 - 
    IC:\Users\CHINGC~1\AppData\Local\Temp\pip-build-env-jsdwuhv9\overlay\Lib\site - 
    packages\numpy\core\include -IC:\\Users\\CHINGC~1\\AppData\\Local\\Temp\\pip-build-env- 
    jsdwuhv9\\overlay\\Lib\\site-packages\\numpy\\core\\include - 
    IC:\Users\ChingChih\Anaconda3\include -IC:\Users\ChingChih\Anaconda3\include -I"C:\Program 
    Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Microsoft Visual 
    Studio 14.0\VC\ATLMFC\INCLUDE" -I"C:\Program Files (x86)\Windows     
    Kits\10\include\10.0.10240.0\ucrt" /Tcstatsmodels/tsa/_stl.c /Fobuild\temp.win-amd64-    
    3.7\Release\statsmodels/tsa/_stl.obj" failed with exit status 2
      ----------------------------------------
    ERROR: Failed building wheel for statsmodels
    Failed to build statsmodels
    ERROR: Could not build wheels for statsmodels which use PEP 517 and cannot be installed directly


I try `pip install statsmodels --upgrade` and hope it would fix the errors of `wheel` , but it seems fail and give me the same error messages.
@bashtage Could you help me to figure out what to do ? Thanks a lot!

**Comment by bashtage** [comment]
https://github.com/Azure/azure-iot-sdk-python/issues/82#issuecomment-436792771

Has the solution. There shouldn't be a need to build from source in
Windows.

**Comment by ChenChingChih** [comment]
still have others errors...

1. 

    Building wheel for statsmodels (PEP 517) ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ChingChih\Anaconda3\python.exe' 'C:\Users\ChingChih\Anaconda3\lib\site- 
    packages\pip\_vendor\pep517\_in_process.py' build_wheel 
    'C:\Users\CHINGC~1\AppData\Local\Temp\tmpezuco17l'
       cwd: C:\Users\CHINGC~1\AppData\Local\Temp\pip-req-build-_lvokhxn

2.

    UPDATING build\lib.win-amd64-3.7\statsmodels/_version.py
    set build\lib.win-amd64-3.7\statsmodels/_version.py to '0.12.0.dev0+136.gc3bd7d369'
     running build_ext
     _stl.obj : warning LNK4197: 指定了多次匯出 'PyInit__stl'，使用第一次的規格
     正在建立程式庫 build\temp.win-amd64-3.7\Release\statsmodels/tsa\_stl.cp37-win_amd64.lib 和物 
     件 build\temp.win-amd64-3.7\Release\statsmodels/tsa\_stl.cp37-win_amd64.exp
     正在產生程式碼
     已完成程式碼產生
     LINK : fatal error LNK1158: 無法執行 'rc.exe'
     error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe 
     /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO 
     /LIBPATH:C:\\Users\\CHINGC~1\\AppData\\Local\\Temp\\pip-build-env 
     -4hm6onoc\\overlay\\Lib\\site-packages\\numpy\\core\\lib 
     /LIBPATH:C:\Users\ChingChih\Anaconda3\libs 
    /LIBPATH:C:\Users\ChingChih\Anaconda3\PCbuild\amd64 /LIBPATH:"C:\Program Files 
     (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Microsoft    
     Visual Studio 14.0\VC\ATLMFC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Windows 
     Kits\10\lib\10.0.18362.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows 
     Kits\10\lib\10.0.18362.0\um\x64" npymath.lib /EXPORT:PyInit__stl build\temp.win-amd64- 
   3.7\Release\statsmodels/tsa/_stl.obj /OUT:build\lib.win-amd64-3.7\statsmodels\tsa\_stl.cp37- 
    win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\statsmodels/tsa\_stl.cp37- 
    win_amd64.lib" failed with exit status 1158
      ----------------------------------------
     ERROR: Failed building wheel for statsmodels
      Failed to build statsmodels
     ERROR: Could not build wheels for statsmodels which use PEP 517 and cannot be installed 
     directly

**Comment by ChenChingChih** [comment]
Finally!!! everything works after I install `MSVC v142 - VS 2019 C++ x64/x86` and `latest  v142 C++ ALT (x86 & x64)`
@bashtage  thaks a lot!

**Comment by bashtage** [comment]
Great.

**Comment by memeplex** [comment]
I'm still having this problem on MacOS (tested in Catalina and Big Sur).

**Comment by memeplex** [comment]
Mmmm this could be because I'm using 3.9?

**Comment by bashtage** [comment]
You probably shouldn't be using 3.9 yet, at least if you need statsmodels.  statsmodels is not tested on 3.9 yet and there are no wheels.  We will wait until all dependencies, including optional ones, have 3.9 wheels before attempting to build.

**Comment by marimelmmv** [comment]
Still have same problem
ERROR: Could not build wheels for statsmodels which use PEP 517 and cannot be installed directly
 installing statsmodels using Anaconda with Python 3.7 and all packages  from Visual Studio Build Tools 2019 installed as well.

**Comment by bashtage** [comment]
You should figure out which pip you are using.  You might be using the wrong one.

**Comment by marimelmmv** [comment]
pip version : 20.3.1

**Comment by marimelmmv** [comment]
![image](https://user-images.githubusercontent.com/67167172/101935791-a61c6280-3bf0-11eb-9446-f30fcff8224f.png)

**Comment by marimelmmv** [comment]
In [3]: print(statsmodels.__version__)
0.12.1

**Comment by bashtage** [comment]
Then statsmodels is working as expected.

**Comment by bashtage** [comment]
Since you are using anaconda, why not run

```
pip uninstall statsmodels -y
pip uninstall statsmodels -y
conda install statsmdoels==0.12.1
```

which will use conda-provided statsmodels.

**Comment by marimelmmv** [comment]
But when I'm trying to import I have an error
![image](https://user-images.githubusercontent.com/67167172/101936219-51c5b280-3bf1-11eb-9e6c-ca7a807996d0.png)

**Comment by marimelmmv** [comment]
and there is no DynamicVar as well

**Comment by bashtage** [comment]
DynamicVar was removed a long time ago.  It was unmaintained and did not work. ordainal_model is new and not released IIRC.

**Comment by marimelmmv** [comment]
Ok, thank you !
I just found this in documentation 
![image](https://user-images.githubusercontent.com/67167172/101937287-b8979b80-3bf2-11eb-845a-15e675ff5418.png)
and thought that smth wrong with my version or compitability.
When to expect ordinal models ?

**Comment by bashtage** [comment]
It will be a while.  I don't see any plans for a release any time soon.  Summer 2021 perhaps.  

If you really need it you can install from master, or install a nightly wheel.

https://anaconda.org/scipy-wheels-nightly/statsmodels

**Comment by marimelmmv** [comment]
> It will be a while. I don't see any plans for a release any time soon. Summer 2021 perhaps.
> 
> If you really need it you can install from master, or install a nightly wheel.
> 
> https://anaconda.org/scipy-wheels-nightly/statsmodels

many thanks!
