### ISSUE TITLE
Issue in ARIMA predict function: unable to predict for future values 

### ISSUE THREAD

**Issue by KaranBagga** [statsmodels/statsmodels#6462]
Hi Find below the code and data set i am using , i am unable to predict the future forecast value using .predict function of model 
error seems to be like :
The `end` argument could not be matched to a' KeyError: 'The `end` argument could not be matched to a location related to the index of the data.'
Kindly help @ChadFulton 

**Code:**

import pandas as pd
import numpy as np
from matplotlib import pyplot
import statsmodels as sm
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima_model import ARIMA
import statistics
from sklearn.metrics import mean_squared_error

shampoo_series= pd.read_csv('subset.csv', 
                                      index_col=0,
                                      parse_dates=True,
                                      squeeze=True)
									 
shampoo_diff1= shampoo_series.diff().fillna(shampoo_series)
shampoo_diff2 = shampoo_diff1.diff().fillna(shampoo_diff1)

#using naive method to predict
#shampoo_naive = pd.concat([shampoo_series,shampoo_series.shift(1)],axis=1)
#print(shampoo_naive)
plot_acf(shampoo_series)
#pyplot.show()
plot_pacf(shampoo_series)
#pyplot.show()

data_train=shampoo_series[0:25]
data_test=shampoo_series[25:]
ARmodel= ARIMA(data_train,order=(2,1,1)).fit()
#data_forecast=ARmodel.forecast(steps=4)[0]

#print(ARmodel.summary())
#print (np.sqrt(mean_squared_error(data_test,data_forecast)))
predict=ARmodel.predict(start=pd.to_datetime('20-01-1981'), end=pd.to_datetime('26-01-1981') ,typ='levels')

print(predict)

**Dataset**
Date,Temp
01-01-1981,20.7
02-01-1981,17.9
03-01-1981,18.8
04-01-1981,14.6
05-01-1981,15.8
06-01-1981,15.8
07-01-1981,15.8
08-01-1981,17.4
09-01-1981,21.8
10-01-1981,20
11-01-1981,16.2
12-01-1981,13.3
13-01-1981,16.7
14-01-1981,21.5
15-01-1981,25
16-01-1981,20.7
17-01-1981,20.6
18-01-1981,24.8
19-01-1981,17.7
20-01-1981,15.5
21-01-1981,18.2
22-01-1981,12.1
23-01-1981,14.4
24-01-1981,16
25-01-1981,16.5
26-01-1981,18.7
27-01-1981,19.4
28-01-1981,17.2

**Comment by ChadFulton** [comment]
You need to use `dayfirst=True` in your `read_csv` call, otherwise Pandas misinterprets your dates as months for the first 12 observations:

```python
shampoo_series= pd.read_csv('subset.csv',
index_col=0,
parse_dates=True,
dayfirst=True,
squeeze=True)
```

**Comment by KaranBagga** [comment]
@ChadFulton : Thanks i already tried changing the date month format , but when i am trying to predict using below : 
 **ARmodel.predict(start=pd.to_datetime('1981-01-27'), end=pd.to_datetime('1981-03-03') ,typ='levels')**

i am getting error :  raise ValueError(
ValueError: Length of passed values is 37, index implies 36

---> But if use start date as '1981-01-26' i am getting results 
why is it that if using date >26 to predict  , i am getting error as above mentioned .

@ChadFulton : Please help here bud much appreciated

**Comment by ChadFulton** [comment]
This might be a bug that we fixed in the most recent release. Can you try
upgrading to v0.11 and see if that works?

**Comment by KaranBagga** [comment]
@ChadFulton  : Hi i did upgrade to latest version 0.11 , but the issue is still there

**Comment by ChadFulton** [comment]
That does look like a bug, thanks for reporting it!

I recommend that you switch to using our new ARIMA model class, which is available at `sm.tsa.arima.ARIMA`. It is going to be the model that we will be primarily supporting going forwards, and your code appears to work using that class. The original `sm.tsa.ARIMA` model class is currently in a "maintenance-only" state, and will eventually be deprecated and removed.
